### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-architect-DuilioAquino10#1]
[PRACTICA_3.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-DuilioAquino10/files/7151532/PRACTICA_3.pdf)

**Comment by IsraelNicolas61** [comment]
Falto conclusión.
Calificación: 16/20 puntos

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
